include.unit_tests(
    'file',
    'engine',
    'helpers', 
    'inflector',
    'element',
    'ajax', 
    'view',
    'controller_view',
    'vector',
    'timer',
    'model',
    'translation',
    'position',
    'delegation',
    'controller',
    'query'
);

include.functional_tests();